version: 2.1

jobs:

  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Generate tests
          command: make all
      - run:
          name: Save tests for deployment
          command: |
            mkdir /tmp/workspace
            cp -r tests /tmp/workspace/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
          - tests

  commit:
    docker:
      - image: circleci/python3.6
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Checkout test repository
        command: |
          git clone git@github.com:ethereum/eth2.0-tests.git
    - run:
        name: Commit generated tests
        command: |
          cp -r /tmp/workspace/tests .
          git add .
          git commit -m "Update generated tests"
